baseURL = "https://brnfgrty.com/"
languageCode = "en-us"
title = "Brian Fogarty"
theme = "brnfgrty"
copyright = "Brian Fogarty"

[params]
repo = "https://github.com/bfogarty/brnfgrty.com"
description = "Boston-based computer scientist, biologist, and coffee drinker."
